// Levels are pictures. One letter per colour, '.' for empty, and every filled
// cell becomes one tile carrying one arrow. `carve.js` works out which way each
// arrow points at load, so nothing but the drawing is authored here.
//
// **Draw portrait, and draw big.** The board is judged on a phone held upright,
// so art wider than it is tall wastes the screen. 11-13 columns by 13-18 rows is
// the working range — enough cells for a shape to actually read. Tiles come out
// small at that size, which is why the board pans and pinch-zooms.
//
// Tile count is the difficulty, so the list runs small to large: ~80 up to ~170.
//
// After editing, check every level still carves:  node unpuzzle/tools/author.mjs

import { PIECE } from './style.js';

const P = PIECE;

export const LEVELS = [
  {
    name: 'wortel',
    art: [
      '..L.....L..',
      '..LL...LL..',
      '...LL.LL...',
      '....LLL....',
      '..OOOOOOO..',
      '.OOOOOOOOO.',
      '.OOOOOOOOO.',
      '.OOOOOOOOO.',
      '..OOOOOOO..',
      '..OOOOOOO..',
      '...OOOOO...',
      '...OOOOO...',
      '....OOO....',
      '....OOO....',
      '.....O.....',
      '.....O.....',
    ],
    palette: { L: P.leaf, O: P.orange },
    seed: 3,
  },

  {
    name: 'labu',
    art: [
      '......L......',
      '.....LWL.....',
      '...OOOOOOO...',
      '..OOOOOOOOO..',
      '.OOOOOOOOOOO.',
      'OOOEEOOOEEOOO',
      'OOOEEOOOEEOOO',
      'OOOOOOOOOOOOO',
      'OOOOEEEEEOOOO',
      '.OOEOOOOOEOO.',
      '..OOOOOOOOO..',
      '...OOOOOOO...',
    ],
    palette: { L: P.leaf, W: P.wood, O: P.orange, E: P.ink },
    seed: 7,
  },

  {
    name: 'bunga',
    art: [
      '...Y..Y..Y...',
      '..YYYYYYYYY..',
      '.YYYYYYYYYYY.',
      'YYYYYWWWYYYYY',
      'YYYYWWWWWYYYY',
      'YYYYWWWWWYYYY',
      'YYYYWWWWWYYYY',
      '.YYYYYYYYYYY.',
      '..YYYYYYYYY..',
      '...Y..Y..Y...',
      '......L......',
      '..LLL.L......',
      '......L.LLL..',
      '......L......',
      '......L......',
      '......L......',
    ],
    palette: { Y: P.amber, W: P.wood, L: P.leaf },
    seed: 11,
  },

  {
    name: 'balon udara',
    art: [
      '.....GGG.....',
      '...YYGGGSS...',
      '..RYYGGGSSV..',
      '.RRYYGGGSSVV.',
      'RRRYYGGGSSVVV',
      'RRRYYGGGSSVVV',
      'RRRYYGGGSSVVV',
      '.RRYYGGGSSVV.',
      '..RYYGGGSSV..',
      '...YYGGGSS...',
      '....YGGGS....',
      '.....W.W.....',
      '....WWWWW....',
      '....WWWWW....',
    ],
    palette: {
      R: P.coral, Y: P.amber, G: P.leaf, S: P.sky, V: P.violet, W: P.wood,
    },
    seed: 5,
  },

  {
    name: 'gurita',
    art: [
      '....VVVVV....',
      '..VVVVVVVVV..',
      '.VVVVVVVVVVV.',
      'VVVEEVVVEEVVV',
      'VVVEEVVVEEVVV',
      'VVVVVVVVVVVVV',
      'VVVVVVVVVVVVV',
      '.VVVVVVVVVVV.',
      '..VVVVVVVVV..',
      '.VV.VV.VV.VV.',
      '.V..V..V..V..',
      '.V..V..V..V..',
    ],
    palette: { V: P.plum, E: P.ink },
    seed: 13,
  },

  {
    name: 'pohon',
    art: [
      '.....LLL.....',
      '...LLLLLLL...',
      '..LLLLLLLLL..',
      '.LLLLLLLLLLL.',
      'LLLLLLLLLLLLL',
      'LLLLLLLLLLLLL',
      '.LLLLLLLLLLL.',
      '..LLLLLLLLL..',
      '...LLLLLLL...',
      '.....LLL.....',
      '.....WWW.....',
      '.....WWW.....',
      '.....WWW.....',
      '....WWWWW....',
      '...WWWWWWW...',
      '..WWWWWWWWW..',
    ],
    palette: { L: P.leaf, W: P.wood },
    seed: 17,
  },

  {
    name: 'apel',
    art: [
      '......W......',
      '.....WW.LL...',
      '.....WLLLLL..',
      '...RRRRRRR...',
      '..RRRRRRRRR..',
      '.RRRRRRRRRRR.',
      'RRRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      '.RRRRRRRRRRR.',
      '..RRRRRRRRR..',
      '..RRR...RRR..',
    ],
    palette: { W: P.wood, L: P.leaf, R: P.coral },
    seed: 19,
  },

  {
    name: 'kaktus',
    art: [
      '.....GGG.....',
      '.....GGG.....',
      '.GGG.GGG.GGG.',
      'GGGG.GGG.GGGG',
      'GGGG.GGG.GGGG',
      'GGGGGGGGGGGGG',
      'GGGGGGGGGGGGG',
      '.GGGGGGGGGGG.',
      '.....GGG.....',
      '.....GGG.....',
      '.....GGG.....',
      '.....GGG.....',
      '..WWWWWWWWW..',
      '..WWWWWWWWW..',
      '...WWWWWWW...',
      '...WWWWWWW...',
    ],
    palette: { G: P.leaf, W: P.wood },
    seed: 23,
  },

  {
    name: 'es krim',
    art: [
      '...PPPPPPP...',
      '..PPPPPPPPP..',
      '.PPPPPPPPPPP.',
      '.PPPPPPPPPPP.',
      'PPPPPPPPPPPPP',
      '.PPPPPPPPPPP.',
      '..PPPPPPPPP..',
      '..WWWWWWWWW..',
      '..WWWWWWWWW..',
      '...WWWWWWW...',
      '...WWWWWWW...',
      '....WWWWW....',
      '....WWWWW....',
      '.....WWW.....',
      '.....WWW.....',
      '......W......',
    ],
    palette: { P: P.pink, W: P.wood },
    seed: 29,
  },

  {
    name: 'jamur',
    art: [
      '...RRRRRRR...',
      '.RRRRRRRRRRR.',
      'RRRRCRRRCRRRR',
      'RRRRCRRRCRRRR',
      'RRRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      '.RRRRRRRRRRR.',
      '...RRRRRRR...',
      '....CCCCC....',
      '....CCCCC....',
      '....CCCCC....',
      '....CCCCC....',
      '...CCCCCCC...',
      '..CCCCCCCCC..',
    ],
    palette: { R: P.coral, C: P.cream },
    seed: 31,
  },

  {
    name: 'nanas',
    art: [
      '.....L.L.....',
      '....LLLLL....',
      '...LLLLLLL...',
      '....LLLLL....',
      '.....LLL.....',
      '...YYYYYYY...',
      '..YYYYYYYYY..',
      '.YYYYYYYYYYY.',
      '.YYYYYYYYYYY.',
      '.YYYYYYYYYYY.',
      '.YYYYYYYYYYY.',
      '.YYYYYYYYYYY.',
      '.YYYYYYYYYYY.',
      '..YYYYYYYYY..',
      '...YYYYYYY...',
      '....YYYYY....',
    ],
    palette: { L: P.leaf, Y: P.amber },
    seed: 37,
  },

  {
    name: 'stroberi',
    art: [
      '....LLLLL....',
      '..LLLLLLLLL..',
      '.LLLLLLLLLLL.',
      '.RRRRRRRRRRR.',
      'RRRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      '..RRRRRRRRR..',
      '..RRRRRRRRR..',
      '...RRRRRRR...',
      '....RRRRR....',
      '.....RRR.....',
      '......R......',
    ],
    palette: { L: P.leaf, R: P.coral },
    seed: 41,
  },

  {
    name: 'anak ayam',
    art: [
      '......R......',
      '.....RRR.....',
      '....RRRRR....',
      '.....YYY.....',
      '...YYYYYYY...',
      '..YYYYYYYYY..',
      '.YYEEYYYEEYY.',
      '.YYEEYYYEEYY.',
      'YYYYYYOYYYYYY',
      'YYYYYOOOYYYYY',
      'YYYYYYYYYYYYY',
      '.YYYYYYYYYYY.',
      '.YYYYYYYYYYY.',
      '..YYYYYYYYY..',
      '...YYYYYYY...',
      '..OO.....OO..',
    ],
    palette: { R: P.coral, Y: P.amber, O: P.orange, E: P.ink },
    seed: 43,
  },

  {
    name: 'kelinci',
    art: [
      '..WW.....WW..',
      '..WWW...WWW..',
      '..WWW...WWW..',
      '..WWW...WWW..',
      '..WWW...WWW..',
      '...WWWWWWW...',
      '..WWWWWWWWW..',
      '.WWWWWWWWWWW.',
      '.WWEEWWWEEWW.',
      '.WWEEWWWEEWW.',
      '.WWWWWPPPWWW.',
      '..WWWWWWWWW..',
      '..WWWWWWWWW..',
      '.WWWWWWWWWWW.',
      '.WWWWWWWWWWW.',
      '..WWWWWWWWW..',
      '..AA.....AA..',
    ],
    palette: { W: P.pink, E: P.ink, P: P.coral, A: P.coral },
    seed: 47,
  },

  {
    name: 'hantu',
    art: [
      '....CCCCC....',
      '..CCCCCCCCC..',
      '.CCCCCCCCCCC.',
      'CCCCCCCCCCCCC',
      'CCCEECCCEECCC',
      'CCCEECCCEECCC',
      'CCCCCCCCCCCCC',
      'CCCCEEEEECCCC',
      'CCCCCCCCCCCCC',
      'CCCCCCCCCCCCC',
      'CCCCCCCCCCCCC',
      'CC.CCC.CCC.CC',
      'C...C...C...C',
    ],
    palette: { C: P.cream, E: P.ink },
    seed: 53,
  },

  {
    name: 'kucing',
    art: [
      '..P.......P..',
      '..PP.....PP..',
      '..PPP...PPP..',
      '.OOOOOOOOOOO.',
      'OOOOOOOOOOOOO',
      'OOOEEOOOEEOOO',
      'OOOEEOOOEEOOO',
      'OOOOOOOOOOOOO',
      'OOOOMMMMMOOOO',
      '.OOOMMMMMOOO.',
      '..OOOMMMOOO..',
      '..OOOOOOOOO..',
      '.OOOOOOOOOOO.',
      '.OOOOOOOOOOO.',
      '..OOOOOOOOO..',
      '..AA.....AA..',
    ],
    palette: { P: P.pink, O: P.orange, E: P.ink, M: P.cream, A: P.amber },
    seed: 59,
  },

  {
    name: 'penguin',
    art: [
      '....IIIII....',
      '..IIIIIIIII..',
      '.IIIIIIIIIII.',
      '.IICIIIIICII.',
      '.IICIIIIICII.',
      '.IIIIOOOIIII.',
      '.IIIIOOOIIII.',
      '.ICCCCCCCCCI.',
      'IICCCCCCCCCII',
      'IICCCCCCCCCII',
      'IICCCCCCCCCII',
      '.ICCCCCCCCCI.',
      '.IICCCCCCCII.',
      '..IIIIIIIII..',
      '...OO...OO...',
    ],
    palette: { I: P.ink, C: P.cream, O: P.orange },
    seed: 61,
  },

  {
    name: 'beruang',
    art: [
      '.WWW.....WWW.',
      'WWWWW...WWWWW',
      'WWWWW...WWWWW',
      '.WWWWWWWWWWW.',
      'WWWWWWWWWWWWW',
      'WWWEEWWWEEWWW',
      'WWWEEWWWEEWWW',
      'WWWWWWWWWWWWW',
      'WWWWCCCCCWWWW',
      '.WWWCCICCWWW.',
      '..WWWCCCWWW..',
      '..WWWWWWWWW..',
      '.WWWWWWWWWWW.',
      '.WWWWWWWWWWW.',
      '..WWWWWWWWW..',
      '.WWW.....WWW.',
    ],
    palette: { W: P.wood, E: P.ink, C: P.cream, I: P.ink },
    seed: 67,
  },
];
